In [7]:
import nltk
from nltk import word_tokenize, sent_tokenize

nltk.download('punkt')

para = "Sunset is the time of day when our sky meets the outer space solar winds. There are blue, pink, and purple swirls, spinning and twisting, like clouds of balloons caught in a whirlwind. The sun moves slowly to hide behind the line of horizon, while the moon races to take its place in prominence atop the night sky."

words = word_tokenize(para)
sentences = sent_tokenize(para)

print("Sentences:", sentences)
print("Words:", words)

Sentences: ['Sunset is the time of day when our sky meets the outer space solar winds.', 'There are blue, pink, and purple swirls, spinning and twisting, like clouds of balloons caught in a whirlwind.', 'The sun moves slowly to hide behind the line of horizon, while the moon races to take its place in prominence atop the night sky.']
Words: ['Sunset', 'is', 'the', 'time', 'of', 'day', 'when', 'our', 'sky', 'meets', 'the', 'outer', 'space', 'solar', 'winds', '.', 'There', 'are', 'blue', ',', 'pink', ',', 'and', 'purple', 'swirls', ',', 'spinning', 'and', 'twisting', ',', 'like', 'clouds', 'of', 'balloons', 'caught', 'in', 'a', 'whirlwind', '.', 'The', 'sun', 'moves', 'slowly', 'to', 'hide', 'behind', 'the', 'line', 'of', 'horizon', ',', 'while', 'the', 'moon', 'races', 'to', 'take', 'its', 'place', 'in', 'prominence', 'atop', 'the', 'night', 'sky', '.']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [8]:
nltk.download('stopwords')
from nltk.corpus import stopwords 
stop_words = set(stopwords.words('english'))

filtered_words = [word for word in words if word.lower() not in stop_words]
print("Filtered Words:", filtered_words)

Filtered Words: ['Sunset', 'time', 'day', 'sky', 'meets', 'outer', 'space', 'solar', 'winds', '.', 'blue', ',', 'pink', ',', 'purple', 'swirls', ',', 'spinning', 'twisting', ',', 'like', 'clouds', 'balloons', 'caught', 'whirlwind', '.', 'sun', 'moves', 'slowly', 'hide', 'behind', 'line', 'horizon', ',', 'moon', 'races', 'take', 'place', 'prominence', 'atop', 'night', 'sky', '.']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
from nltk import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

pos_tags = pos_tag(filtered_words)
print(pos_tags)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

[('Sunset', 'JJ'), ('time', 'NN'), ('day', 'NN'), ('sky', 'JJ'), ('meets', 'NNS'), ('outer', 'RB'), ('space', 'NN'), ('solar', 'JJ'), ('winds', 'NNS'), ('.', '.'), ('blue', 'NN'), (',', ','), ('pink', 'NN'), (',', ','), ('purple', 'JJ'), ('swirls', 'NN'), (',', ','), ('spinning', 'VBG'), ('twisting', 'NN'), (',', ','), ('like', 'IN'), ('clouds', 'JJ'), ('balloons', 'NNS'), ('caught', 'VBD'), ('whirlwind', 'NN'), ('.', '.'), ('sun', 'NN'), ('moves', 'NNS'), ('slowly', 'RB'), ('hide', 'VBP'), ('behind', 'IN'), ('line', 'NN'), ('horizon', 'NN'), (',', ','), ('moon', 'NN'), ('races', 'NNS'), ('take', 'VBP'), ('place', 'NN'), ('prominence', 'NN'), ('atop', 'JJ'), ('night', 'NN'), ('sky', 'NN'), ('.', '.')]

In [10]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]
print(stemmed_words)

['sunset', 'tim', 'day', 'sky', 'meet', 'out', 'spac', 'sol', 'wind', '.', 'blu', ',', 'pink', ',', 'purpl', 'swirl', ',', 'spin', 'twist', ',', 'lik', 'cloud', 'balloon', 'caught', 'whirlwind', '.', 'sun', 'mov', 'slow', 'hid', 'behind', 'lin', 'horizon', ',', 'moon', 'rac', 'tak', 'plac', 'promin', 'atop', 'night', 'sky', '.']

In [11]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def get_wordnet_tag(tag):
    if tag.startswith('J'):
        return 'a'
    elif tag.startswith('N'):
        return 'n'
    elif tag.startswith('R'):
        return 'r'
    elif tag.startswith('V'):
        return 'v'
    else:
        return 'n'
    
lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_tag(tag)) for word,tag in pos_tags]

print(lemmatized_words)

['Sunset', 'time', 'day', 'sky', 'meet', 'outer', 'space', 'solar', 'wind', '.', 'blue', ',', 'pink', ',', 'purple', 'swirl', ',', 'spin', 'twisting', ',', 'like', 'clouds', 'balloon', 'catch', 'whirlwind', '.', 'sun', 'move', 'slowly', 'hide', 'behind', 'line', 'horizon', ',', 'moon', 'race', 'take', 'place', 'prominence', 'atop', 'night', 'sky', '.']

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

corpus = sentences

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(corpus)

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

print("TF-IDF Matrix:")
display(tfidf_df)

top_words = tfidf_df.sum().sort_values(ascending=False)
display(top_words.to_frame(name="score"))

TF-IDF Matrix:

,and,are,atop,balloons,behind,blue,caught,clouds,day,hide,...,take,the,there,time,to,twisting,when,while,whirlwind,winds
0,0.00000,0.00000,0.000000,0.00000,0.000000,0.00000,0.00000,0.00000,0.264992,0.000000,...,0.000000,0.403066,0.00000,0.264992,0.000000,0.00000,0.264992,0.000000,0.00000,0.264992
1,0.47236,0.23618,0.000000,0.23618,0.000000,0.23618,0.23618,0.23618,0.000000,0.000000,...,0.000000,0.000000,0.23618,0.000000,0.000000,0.23618,0.000000,0.000000,0.23618,0.000000
2,0.00000,0.00000,0.180305,0.00000,0.180305,0.00000,0.00000,0.00000,0.000000,0.180305,...,0.180305,0.548505,0.00000,0.000000,0.360609,0.00000,0.000000,0.180305,0.00000,0.000000

               score
the         0.951571
and         0.472360
of          0.402491
to          0.360609
sky         0.338659
in          0.316747
meets       0.264992
our         0.264992
sunset      0.264992
outer       0.264992
day         0.264992
is          0.264992
time        0.264992
space       0.264992
solar       0.264992
when        0.264992
winds       0.264992
there       0.236180
twisting    0.236180
blue        0.236180
caught      0.236180
clouds      0.236180
are         0.236180
balloons    0.236180
spinning    0.236180
swirls      0.236180
whirlwind   0.236180
purple      0.236180
pink        0.236180
like        0.236180
its         0.180305
horizon     0.180305
hide        0.180305
behind      0.180305
atop        0.180305
line        0.180305
night       0.180305
moves       0.180305
slowly      0.180305
races       0.180305
place       0.180305
prominence  0.180305
moon        0.180305
sun         0.180305
take        0.180305
while       0.180305